version: "3.8"
services:
  discordfilter:
    image: discordfilter:latest
    networks:
      - discordfilter
    volumes:
      - ./db_data:/var/lib/mysql
    tty: true
    stdin_open: true
    environment:
      BOT_TOKEN: MTE4MTc0OTg0ODI1MzQxNTUxNQ.GvmFCO.uCvgywNOoMaYpQd49m7Fd-Mr4ndZ1pwz6fg6SU
networks:
  discordfilter:
